// export const CART_ACTION_TYPES = {
//   SET_CART: "cart/SET_CART",
// };

export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  SET_DROPDOWN_VISIBILITY: "cart/SET_DROPDOWN_VISIBILITY",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
  SET_CART_TOTAL: "cart/SET_CART_TOTAL",
};
